# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Still thinking about what to write.

# Theme Secondary subtitle
susbtitle_secondary: Come disvocer more.

# Footer About Section
about_footer: All rights reserved <a href="https://github.com/kylops" target="_blank">kylops</a>.<br />The source code is available on <a href="https://github.com/kylops/vv3schools-blog" target="_blank">GitHub</a>.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "https://picsum.photos/g/450/450?blur?random"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: kylops
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
instagram_url: https://www.instagram.com/
github_url: https://github.com/kylops
email_url: info@vv3schools.com

node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false